// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type ExecuteReq struct {
	InputList []string `json:"inputList"`
	Code      string   `json:"code"`
	Language  string   `json:"language"`
}

type ExecuteResp struct {
	OutputList           []string `json:"outputList"`
	Message              string   `json:"message"`
	Status               int64    `json:"status"`
	ExecuteResultMessage string   `json:"executeResultMessage"`
	ExecuteResultTime    int64    `json:"executeResultTime"`
	ExecuteResultMemory  int64    `json:"executeResultMemory"`
}
