// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: sandbox.proto

package server

import (
	"context"

	"gyu-oj-sandbox/cmd/rpc/internal/logic"
	"gyu-oj-sandbox/cmd/rpc/internal/svc"
	"gyu-oj-sandbox/cmd/rpc/pb"
)

type CodeSandboxServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCodeSandboxServer
}

func NewCodeSandboxServer(svcCtx *svc.ServiceContext) *CodeSandboxServer {
	return &CodeSandboxServer{
		svcCtx: svcCtx,
	}
}

func (s *CodeSandboxServer) ExecuteCode(ctx context.Context, in *pb.ExecuteCodeReq) (*pb.ExecuteCodeResp, error) {
	l := logic.NewExecuteCodeLogic(ctx, s.svcCtx)
	return l.ExecuteCode(in)
}
